imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SundayUserBundle/Resources/config/services.yml" }
    - { resource: "@SundayOrganizationBundle/Resources/config/services.yml" }
    - { resource: "@SundayWitchcraftBundle/Resources/config/services.yml" }
    - { resource: "@SundayPostBundle/Resources/config/services.yml" }
    - { resource: "@SundayMediaBundle/Resources/config/services.yml" }
    - { resource: "@SundayForumBundle/Resources/config/services.yml" }
    - { resource: "@SundayUIBundle/Resources/config/services.yml" }
    - { resource: "@SundayCommandBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    upload_maxsize: 200k

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SundayUIBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        alias: GedmoTree
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sunday\UserBundle\Entity\User
    use_listener: false
    registration:
        form:
            type: Sunday\UserBundle\Form\Type\RegistrationType

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - { db_table: sunday_session, db_username: '%database_user%', db_password: '%database_password%' }

jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            #extractors: [alias_of_the_extractor]

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: SundayUIBundle:Pagination:semantic_ui_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

liip_imagine:
    resolvers:
        defaults:
            web_path: ~

    filter_sets:
        cache: ~
        avatar_thumb:
            quality: 80
            filters:
                thumbnail: { size: [160, 160], mode: inset }

gos_web_socket:
    server:
        port: 8080
        host: 127.0.0.1
        router:
            resources:
                - @SundayForumBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main
        session_handler: @session.handler.pdo
    pushers:
        wamp:
            host: 127.0.0.1
            port: 1337
