<?php

namespace Sunday\MediaBundle\Repository;

/**
 * AbstractFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractFileRepository extends \Doctrine\ORM\EntityRepository
{
}
