<?php

namespace Sunday\MediaBundle\Repository;

/**
 * FileCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
