<?php

namespace Sunday\MediaBundle\Repository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends \Doctrine\ORM\EntityRepository
{
}
