<?php

namespace Sunday\MediaBundle\Repository;

/**
 * GalleryCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
