<?php

namespace Sunday\OrganizationBundle\Repository;

/**
 * BusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
