<?php

namespace Sunday\WitchcraftBundle\Repository;

/**
 * WitchcraftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitchcraftRepository extends \Doctrine\ORM\EntityRepository
{
}
