<?php

namespace Sunday\WitchcraftBundle\Repository;

/**
 * WitchcraftLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitchcraftLogRepository extends \Doctrine\ORM\EntityRepository
{
}
