<?php

namespace Sunday\PostBundle\Repository;

/**
 * CommentPostscriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPostscriptRepository extends \Doctrine\ORM\EntityRepository
{
}
