<?php

namespace Sunday\PostBundle\Repository;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
