<?php

namespace Sunday\PostBundle\Repository;

/**
 * PostscriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostscriptRepository extends \Doctrine\ORM\EntityRepository
{
}
